# Generated by Django 4.2.27 on 2025-12-22 07:12

from django.db import migrations

def create_default_types(apps, schema_editor):
    TodoType = apps.get_model('todo_api', 'TodoType')
    TodoType.objects.create(name='Simple Task', description='A standard todo item')
    TodoType.objects.create(name='Reminder', description='A time-sensitive reminder')

def remove_default_types(apps, schema_editor):
    TodoType = apps.get_model('todo_api', 'TodoType')
    TodoType.objects.filter(name__in=['Simple Task', 'Reminder']).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('todo_api', '0003_todotype_todo_todo_type'),
    ]

    operations = [
        migrations.RunPython(create_default_types, remove_default_types),
    ]
